version: '3.9'

services:
  config-server:
    build:
      context: ../config-server
      dockerfile: Dockerfile
    image: config-server:latest
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL","curl --fail http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  employee-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-service:latest
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      SPRING_CONFIG_IMPORT:    "configserver:http://config-server:8888"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      SPRING_PROFILES_ACTIVE:  docker

volumes:
  db-data:
